# hugo server --minify --themesDir ../.. --baseURL=http://0.0.0.0:1313/theme/hugo-book/
# （启动命令：压缩输出，主题目录为 ../..，基本 URL 为 http://0.0.0.0:1313/theme/hugo-book/）

baseURL = 'https://mushan169-github-io.pages.dev/'
title = '天体观测'
theme = 'hugo-book'
languageCode = 'zh-cn'




# 开启文章分类
[taxonomies]
  category = 'categories'
  tag = 'tags'

# 开启分页设置
pagination.pagerSize = 10
pagination.paginatePath = 'blog'

# 书籍配置
disablePathToLower = true
enableGitInfo = true 

# 摘要自动生成的字符长度
summaryLength = 70


# mermaid/katex 短代码所需设置
[markup]
[markup.goldmark.renderer]
  unsafe = true


[markup.postCSS]
  use = ["postcss"]
    includePaths = ["assets/css"]

[markup.tableOfContents]
  startLevel = 1

# 多语言模式配置
# 翻译文件有多种选项
# 参见 https://gohugo.io/content-management/multilingual/#translation-by-filename
# 以及 https://gohugo.io/content-management/multilingual/#translation-by-content-directory


[menu]
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.after]]
  name = "Record"
  url = "/record/"
  weight = 2

[[menu.after]]
  name = "Blog"
  url = "/blog/"
  weight = 3
  
[[menu.after]]
  name = "Daily"
  url = "/daily/"
  weight = 4

[[menu.after]]
  name = "Draw"
  url = "/draw/"
  weight = 5

[[menu.after]]
name = "Read"
url = "/read/"
weight = 6

[[menu.after]]
  name = "Profile"
  url = "/about/"
  weight = 7


[params]
  author = "SODA/MUSHAN0413"

  # light、dark、auto（auto跟随系统主题）
  BookTheme = 'auto'

  # （可选，默认 true）控制页面右侧目录的显示。
  # 目录的起始和结束级别可通过 markup.tableOfContents 设置进行控制。
  # 你也可以在每个页面的 Front Matter 中单独指定此参数。
  # $BookToC = true

  # （可选，默认 favicon.png）设置 favicon 文件的路径。
  # 如果 favicon 位于 /static/favicon.png，则路径为 favicon.png
  # BookFavicon = '/static/img/favicon.ico'

  # BookLogo = 'logo.png'


  # BookSection = ''

  BookRepo = 'https://github.com/mushan169/mushan169.github.io'


  BookCommitPath = 'commit'

  # BookEditPath = 'edit/main/exampleSite'

  BookDateFormat = 'January 2, 2006'

  BookSearch = true

  BookComments = true

